export const routes = {
  FAQ: '/faq',
  SIGN_IN: '/',
  HOME: '/home',
  BIKE: '/bike',
  SHOP: '/shop',
  ORDER: '/order',
  FILTER: '/filter',
  REVIEWS: '/reviews',
  SIGN_UP: '/sign-up',
  PROFILE: '/profile',
  SIGN_OUT: '/sign-out',
  WISHLIST: '/wishlist',
  PAYMENTS: '/payments',
  CARD_MENU: '/card-menu',
  CATEGORIES: '/categories',
  STATISTICS: '/statistics',
  INFO_SAVED: '/info-saved',
  CART_EMPTY: '/cart-empty',
  DESCRIPTION: '/description',
  IBAN_PAYMENT: '/iban-payment',
  CARD_DETAILS: '/card-details',
  INVOICE_SENT: '/invoice-sent',
  OPEN_DEPOSIT: '/open-deposit',
  NEW_PASSWORD: '/new-password',
  ORDER_FAILED: '/order-failed',
  OPEN_MONEYBOX: '/open-moneybox',
  TAB_NAVIGATOR: '/tab-navigator',
  FUND_TRANSFER: '/fund-transfer',
  OPEN_NEW_LOAN: '/open-new-loan',
  OPEN_NEW_CARD: '/open-new-card',
  WISHLIST_EMPTY: '/wishlist-empty',
  PAYMENT_FAILED: '/payment-failed',
  EXCHANGE_RATES: '/exchange-rates',
  CREATE_INVOICE: '/create-invoice',
  TOP_UP_PAYMENT: '/top-up-payment',
  MOBILE_PAYMENT: '/mobile-payment',
  PRIVACY_POLICY: '/privacy-policy',
  PAYMENT_SUCCESS: '/payment-success',
  FORGOT_PASSWORD: '/forgot-password',
  CHANGE_PIN_CODE: '/change-pin-code',
  ORDER_SUCCESSFUL: '/order-successful',
  CONFIRMATION_CODE: '/confirmation-code',
  EDIT_PERSONAL_INFO: '/edit-personal-info',
  TRANSACTION_HISTORY: '/transaction-history',
  TRANSACTION_DETAILS: '/transaction-details',
  STATISTICS_CHOOSE_CARD: '/statistics-choose-card',
  SIGN_UP_ACCOUNT_CREATED: '/sign-up-account-created',
  EMAIL_HAS_BEEN_VERIFIED: '/email-has-been-verified',
  VERIFY_YOUR_PHONE_NUMBER: '/verify-your-phone-number',
  FORGOT_PASSWORD_SENT_EMAIL: '/forgot-password-sent-email',
  PHONE_NUMBER_HAS_BEEN_VERIFIED: '/phone-number-has-been-verified',
};

// export const tabRoutes = {
//   HOME: '/tab-navigator/home',
//   CATEGORIES: '/tab-navigator/categories',
//   ORDER: '/tab-navigator/order',
//   WISHLIST: '/tab-navigator/wishlist',
//   PROFILE: '/tab-navigator/profile',
// };
